Windows compatability
digiLab-ai/twinLab-client pull request #25
Opened 2023-07-18 10:04 UTC by TimJillians

Changed the `basic.ipynb` and `ukaea.ipynb` files slightly to ensure windows compatability.

2023-07-20 08:43 UTC, alexander-mead requested changes
Looks really good! Thanks for the bug fix for the JSON decode, and the notebook is very useful.

Please unrun the notebook and re-push (this makes the commit for the notebooks look cleaner).

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "This notebook contains an example of when the model is fed two features. In the training data, $y = sin(X_1)$. $X_2$ has no correlation to $y$ whatsoever, and is just random numbers. We are test
Use \sin for the sine function in LaTeX

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "This notebook contains an example of when the model is fed two features. In the training data, $y = sin(X_1)$. $X_2$ has no correlation to $y$ whatsoever, and is just random numbers. We are test
Is there any noise in the relationship between $y$ and $X_1$ here?

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "This notebook contains an example of when the model is fed two features. In the training data, $y = sin(X_1)$. $X_2$ has no correlation to $y$ whatsoever, and is just random numbers. We are test
"one of the features is random" -> "one of the features contains no information"

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "- $y$ is $sin(X_1)$ and has no dependency on $X_2$ whatsoever. \n",
$y=\sin(X_1)$ (any noise here? if not, it would be nice to add some Gaussian scatter with sig = 0.05 or so.

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "In this cell we set the parameters we are going to train the model on."
"In this cell we set the parameters to be used for training the model."

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "- The $X_1$ values are 101 equally spaced numbers between 0 and 1. We convert this array to a list.\n",
Do you convert to a list? You probably don't need to.

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "- The $X_2$ values are 101 random values between 0 and 1. They are stored in an array so we `.ravel()` them to make them a 1D list which is required for the next step.\n",
I think you can probably avoid `.ravel()` here

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "This cell trains the model on the dataset we provided, and within the parameters we provided."
and within the parameters we provided -> using the parameters we provided

2023-07-20 08:43 UTC, alexander-mead commented on notebooks/second_random_input.ipynb
> +    "This step is where the model takes in the $X_1$ and $X_2$ values we gave it and based on the training data, it predicts the corresponding $y$ value. `df_mean` is the value the model predicts. `d
"This step is where the model takes in the $X_1$ and $X_2$ values we gave it and based on the training data, it predicts the corresponding $y$ value. `df_mean` is the value the model predicts. `df_std` is how uncertain the model is about the `df_mean` value, where `df_mean` could be anywhere plus or minus the `df_std` value."

->

"Here we ingest $X_1$ and $X_2$ values and, based on the training data, make predictions for the corresponding $y$ value. `df_mean` is the mean value that the model predicts, while `df_std` an estimate of the uncertainty of the model around the `df_mean` value. There is around a $68\%$ chance that values lie within `df_std` of `df_mean`, which rises to $95\%$ within `2*df_std`.

2023-07-20 09:46 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "This notebook contains an example of when the model is fed two features. In the training data, $y = sin(X_1)$. $X_2$ has no correlation to $y$ whatsoever, and is just random numbers. We are test
I have added some noise to $y$ to make it more realistic

2023-07-21 13:21 UTC, alexander-mead commented
Great working with you this week Tim. Let me know if you get a chance to implement the minor fixes in the "requested changes", and then I will merge your pull request into the main `twinLab-client`. No problems if you don't have time though, I can do it first thing next week.

2023-07-21 14:07 UTC, TimJillians commented
> Hi Alexander, I am going to try and implement them now. Thank you for helping me this week and I hope you have a good weekend. I am going to start the blog post hopefully as well.

2023-07-21 14:09 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "This notebook contains an example of when the model is fed two features. In the training data, $y = sin(X_1)$. $X_2$ has no correlation to $y$ whatsoever, and is just random numbers. We are test
Done. I will push alongside the other changes

2023-07-21 14:15 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "- $y$ is $sin(X_1)$ and has no dependency on $X_2$ whatsoever. \n",
I have added some using `+ np.random.normal(0, 0.05, 10)`.

2023-07-21 14:16 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "In this cell we set the parameters we are going to train the model on."
Done

2023-07-21 14:20 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "- The $X_1$ values are 101 equally spaced numbers between 0 and 1. We convert this array to a list.\n",
I think that markdown was wrong; I never did convert to a list. I have removed the parts referring to lists.

2023-07-21 14:21 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "This cell trains the model on the dataset we provided, and within the parameters we provided."
Done

2023-07-21 14:26 UTC, TimJillians commented on notebooks/second_random_input.ipynb
> +    "This step is where the model takes in the $X_1$ and $X_2$ values we gave it and based on the training data, it predicts the corresponding $y$ value. `df_mean` is the value the model predicts. `d
I have changed this. Did you mean to have $68$% and $95$%? I think the maths font/language doesn't display the percentage signs. Or is this a convention? Thanks

2023-07-21 15:17 UTC, TimJillians commented
I should have fixed all the requested changes. You should be able to merge it now, I hope. Thank you!

2023-07-24 08:09 UTC, merged