Iss39 active learning
digiLab-ai/twinLab-client pull request #42
Opened 2023-08-24 16:10 UTC by michellebieger

Thank you for your help Alexander!

Features new candidate_points_campaign implementing the active learning from the backend. 

Also includes more detailed error messaging on the client-side.

2023-08-29 14:33 UTC, alexander-mead requested changes

2023-08-29 14:33 UTC, alexander-mead commented on scripts/api/get_candidate_points_model.py
Looks good!

2023-08-29 16:31 UTC, alexander-mead approved these changes

2023-08-29 16:32 UTC, alexander-mead commented
This is good to go from my point of view. @FreddyWordingham I won't merge, but you should feel free to.

2023-08-29 22:57 UTC, FreddyWordingham commented
Everything working on my branch and in monolith

One note: `api_key` needs to be `api-key` (the AWS HTTP Gateway changes `-` to `_` -.- )

2023-08-30 07:14 UTC, alexander-mead commented
Thanks API gateway, thanks. 😀

On Tue, 29 Aug 2023 at 23:58, Freddy Wordingham ***@***.***>
wrote:

> Everything working on my branch and in monolith
>
> One note: api_key needs to be api-key (the AWS HTTP Gateway changes - to _
> -.- )
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/digiLab-ai/twinLab-client/pull/42#issuecomment-1698250297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACFXVYNZRJMRBC6S3YPRZTLXXZXXXANCNFSM6AAAAAA35ILRFM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-08-31 15:44 UTC, merged